"""API models for the Detection & Correlation service."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field


Severity = Literal["low", "medium", "high", "critical"]
RuleType = Literal["single_event", "sequence", "behavioural_deviation", "cross_domain"]
FindingState = Literal["open", "superseded", "dismissed", "escalated"]


class ProcessLineage(BaseModel):
    """Simplified process lineage for correlation."""

    parent_process: Optional[str] = Field(default=None, max_length=200)
    process_name: Optional[str] = Field(default=None, max_length=200)
    command_line: Optional[str] = Field(default=None, max_length=500)


class NetworkFlow(BaseModel):
    """Network flow metadata captured for correlation."""

    direction: Optional[Literal["inbound", "outbound"]] = None
    destination: Optional[str] = Field(default=None, max_length=200)
    destination_port: Optional[int] = Field(default=None, ge=1, le=65535)


class NormalisedEvent(BaseModel):
    """Normalised event schema provided by MVP-7."""

    event_id: str = Field(..., min_length=3, max_length=120)
    tenant_id: str = Field(..., min_length=3, max_length=64)
    asset_id: str = Field(..., min_length=3, max_length=64)
    identity_id: str = Field(..., min_length=3, max_length=64)
    event_type: str = Field(..., min_length=3, max_length=120)
    occurred_at: datetime
    received_at: datetime
    attributes: dict[str, Any] = Field(default_factory=dict)
    process_lineage: Optional[ProcessLineage] = None
    network_flow: Optional[NetworkFlow] = None


class TelemetryBaseline(BaseModel):
    """Telemetry baselines from MVP-4."""

    metric_name: str = Field(..., min_length=2, max_length=120)
    baseline_value: float = Field(..., ge=0)
    window_seconds: int = Field(..., ge=60, le=86400)


class PatchState(BaseModel):
    """Patch and system state from MVP-6."""

    missing_patches: list[str] = Field(default_factory=list)
    last_patch_scan: datetime
    exposure: Literal["internet", "internal", "restricted"] = "internal"


class AssetMetadata(BaseModel):
    """Asset metadata from MVP-3."""

    asset_id: str = Field(..., min_length=3, max_length=64)
    hostname: Optional[str] = Field(default=None, max_length=120)
    environment: Literal["production", "staging", "development", "unknown"] = "unknown"
    criticality: Literal["low", "medium", "high"] = "medium"


class IdentityContext(BaseModel):
    """Identity metadata (roles and privileges)."""

    identity_id: str = Field(..., min_length=3, max_length=64)
    display_name: Optional[str] = Field(default=None, max_length=120)
    role: Optional[str] = Field(default=None, max_length=120)
    privileges: list[str] = Field(default_factory=list)


class ContextSnapshot(BaseModel):
    """Combined context required for decision making."""

    asset: AssetMetadata
    identity: IdentityContext
    baseline: Optional[TelemetryBaseline] = None
    patch_state: Optional[PatchState] = None
    maintenance_window: bool = False


class RuleSuppression(BaseModel):
    """Suppression configuration for a rule."""

    dedupe_window_seconds: int = Field(default=900, ge=60, le=86400)
    allowlist_assets: list[str] = Field(default_factory=list)
    allowlist_identities: list[str] = Field(default_factory=list)
    allowlist_event_types: list[str] = Field(default_factory=list)


class RuleOutputTemplate(BaseModel):
    """Output template for a finding generated by a rule."""

    finding_type: str = Field(..., min_length=3, max_length=120)
    severity: Severity
    confidence_base: float = Field(..., ge=0, le=1)
    explanation_template: str = Field(..., min_length=10, max_length=800)


class RuleDefinition(BaseModel):
    """Declarative rule definition for the detection engine."""

    rule_id: str = Field(..., min_length=3, max_length=120)
    version: str = Field(..., min_length=1, max_length=40)
    name: str = Field(..., min_length=3, max_length=200)
    description: str = Field(..., min_length=10, max_length=800)
    rule_type: RuleType
    enabled: bool = True
    trigger_event_types: list[str] = Field(default_factory=list)
    sequence_event_types: list[str] = Field(default_factory=list)
    time_window_seconds: Optional[int] = Field(default=None, ge=60, le=86400)
    deviation_multiplier: Optional[float] = Field(default=None, ge=1.1, le=50)
    required_context: list[str] = Field(default_factory=list)
    suppression: RuleSuppression = Field(default_factory=RuleSuppression)
    output: RuleOutputTemplate


class CorrelationNode(BaseModel):
    """Node representing event or entity in the correlation graph."""

    node_id: str = Field(..., min_length=3, max_length=120)
    node_type: Literal["event", "asset", "identity", "process", "network"]
    label: str = Field(..., min_length=2, max_length=200)


class CorrelationEdge(BaseModel):
    """Edge capturing relationships for correlation."""

    source: str = Field(..., min_length=3, max_length=120)
    target: str = Field(..., min_length=3, max_length=120)
    relationship: str = Field(..., min_length=3, max_length=120)


class CorrelationGraph(BaseModel):
    """Correlation graph for a finding."""

    nodes: list[CorrelationNode] = Field(default_factory=list)
    edges: list[CorrelationEdge] = Field(default_factory=list)


class Finding(BaseModel):
    """Immutable finding produced by MVP-8."""

    finding_id: UUID
    finding_type: str
    severity: Severity
    confidence_score: float
    supporting_events: list[str]
    correlation_graph: CorrelationGraph
    context_snapshot: ContextSnapshot
    explanation_text: str
    creation_timestamp: datetime
    state: FindingState = "open"
    superseded_by: Optional[UUID] = None


class FindingResponse(BaseModel):
    status: Literal["created"]
    finding: Finding


class FindingListResponse(BaseModel):
    findings: list[Finding]


class EventIngestRequest(BaseModel):
    event: NormalisedEvent
    context: Optional[ContextSnapshot] = None


class EventIngestResponse(BaseModel):
    status: Literal["processed"]
    findings: list[Finding]


class RuleResponse(BaseModel):
    status: Literal["recorded"]
    rule: RuleDefinition


class RuleListResponse(BaseModel):
    rules: list[RuleDefinition]


class DismissFindingRequest(BaseModel):
    identity_id: str = Field(..., min_length=3, max_length=64)
    reason: str = Field(..., min_length=10, max_length=500)
    dismissed_at: datetime


class DismissFindingResponse(BaseModel):
    status: Literal["dismissed"]
    finding_id: UUID
    dismissed_at: datetime


class SuppressionDecision(BaseModel):
    """Audit record for suppression decisions."""

    decision_id: UUID
    rule_id: str
    event_id: str
    asset_id: str
    identity_id: str
    reason: str
    suppressed_at: datetime
